kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqlvolume
  labels:
    app: quotes-app
    app.kubernetes.io/part-of: quotes-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rbd-storagepool-cluster
  volumeMode: Filesystem
